name: "Chargrill Charlie's"
favicon: null
layout_spectrum: 0.7524657815229148
typography_spectrum: 0.6935874989721924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.869189215824008
  lightness: 0.836492968024686
  saturation: 0.36594005674123764
  rhythmicContrast: 0.9868655558675528
purpose: []
